project:
  type: website

website:
  title: "Geog385F23"
  image: img/logo.png
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: lectures
        text: Lectures

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



