---
title: "Geography 385 Spatial Data Analysis"
subtitle: "Fall 2023"
format:
  html:
    theme: cosmo 
  pdf:
    colorlinks: true
---


## Lectures

- Week 01
  - [08-21 Course Introduction](week-01/01-introduction.qmd)
  - [08-23 Jupyter Introduction](week-01/2023-08-23.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-01/2023-08-23.ipynb)


- Week 02

  - [08-28 Python Introduction](week-02/2023-08-28-python-introduction.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-02/2023-08-28-python-introduction.ipynb)
  - [08-30 Functions and Scripts](week-02/2023-08-30-functions-scripts.ipynb)
    [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-02/2023-08-30-functions-scripts.ipynb)
    [(temp_converter.py)](https://github.com/sjsrey/385f23/blob/main/lectures/week-02/temp_converter.py)


- Week 03

  - [09-06 Python Introduction to Data Analysis](week-03/2023-09-06.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-03/2023-09-06.ipynb)

- Week 04

  - [09-11 Spatial Data](week-04/2023-09-11-spatial-data.qmd)
  - [09-13 GeoPandas](week-04/2023-09-13.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-04/2023-09-13.ipynb)

  
- Week 05

  - [09-18 GeoPandas Spatial Queries](week-05/2023-09-18.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-05/2023-09-18.ipynb)
  - [09-20 Geovisualization](week-05/2023-09-20.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-05/2023-09-20.ipynb)


- Week 06

  - [09-25 Spatial Weights](week-06/2023-09-25.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-06/2023-09-25.ipynb)
  - [09-27 Spatial Dependence](week-06/2023-09-27.qmd)


- Week 07

  - [10-02 Join Counts](week-07/2023-10-02.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-07/2023-10-02.ipynb)
  - [10-04 Moran's I](week-07/2023-10-04.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-07/2023-10-04.ipynb)

- Week 08
  - 10-09 Studio (Exercise 2 collaboration)
  - [10-11 Local Autocorrelation](week-08/2023-10-11.ipynb) [(ipynb)](https://github.com/sjsrey/385f23/blob/main/lectures/week-08/2023-10-11.ipynb)


- Week 09
  - [11-16 Local Analysis of Educational Achievment](https://knaaptime.com/instructed_california/)
  - [11-18 Point Patterns](week-09/2023-10-18-point-patterns.qmd) 
